### ISSUE TITLE
Upload page

### ISSUE THREAD

**Issue by andrey1103** [HDInnovations/UNIT3D#641] opened 2019-03-12 19:03 UTC
### Issue Type
- [x] Feature Idea

On upload page you have category and type , but for games/music category  remains the same type from movies like uhd , 720p , you should add new type for games and music.

**Comment by HDVinnie** [comment] 2019-03-12 19:06
You can add your own types from staff_dashboard and this is a duplicate of https://github.com/HDInnovations/UNIT3D/issues/237 . Please check for existing issues before opening one.

**Closed by HDVinnie** 2019-03-12 19:06 UTC
Labels: Duplicate
